server:
  port: 8777
  adress: 0.0.0.0
  servlet:
    context-path: /group


spring:
  datasource:
    url: jdbc:mysql://cdb-b6fcgmw2.cd.tencentcdb.com:10053/TOFEL?serverTimezone=UTC&characterEncoding=utf-8
    hikari:
      username: groupsix
      password: chinasoft6
      driver-class-name: com.mysql.cj.jdbc.Driver
  http:
    multipart:

mybatis:
  mapper-locations: classpath:chatmodule/mapper/*.xml
  type-aliases-package: chatmodule.bean